TickerList:                             
  -
    TickerIndex: 0
    Ticker: 000001.SZ
    
  -
    TickerIndex: 1
    Ticker: 000002.SZ

  -
    TickerIndex: 2
    Ticker: 000004.SZ

  -
    TickerIndex: 3
    Ticker: 000005.SZ

  -
    TickerIndex: 4
    Ticker: 000006.SZ

  -
    TickerIndex: 5
    Ticker: 000007.SZ

  -
    TickerIndex: 6
    Ticker: 000008.SZ

  -
    TickerIndex: 7
    Ticker: 002001.SZ

  -
    TickerIndex: 8
    Ticker: 300001.SZ

  -
    TickerIndex: 9
    Ticker: 600000.SH

  -
    TickerIndex: 10
    Ticker: 600004.SH
    
  -
    TickerIndex: 11
    Ticker: 600005.SH

  -
    TickerIndex: 12
    Ticker: 600006.SH

  -
    TickerIndex: 13
    Ticker: 600007.SH

  -
    TickerIndex: 14
    Ticker: 600008.SH

  -
    TickerIndex: 15
    Ticker: 600009.SH

  -
    TickerIndex: 16
    Ticker: 600010.SH

  -
    TickerIndex: 17
    Ticker: 688001.SH

  -
    TickerIndex: 18
    Ticker: 688002.SH

  -
    TickerIndex: 19
    Ticker: 159901.SZ

  -
    TickerIndex: 20
    Ticker: 123010.SZ

  -
    TickerIndex: 21
    Ticker: 131801.SZ

  -
    TickerIndex: 22
    Ticker: 510050.SH

  -
    TickerIndex: 23
    Ticker: 113017.SH

  -
    TickerIndex: 24
    Ticker: 204001.SH