TickerList:                             
  -
    TickerIndex: 0
    Ticker: IC209
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 1
    Ticker: IC2510
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 2
    Ticker: IC2512
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 3
    Ticker: IC2603
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 4
    Ticker: IF2509
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 5
    Ticker: IF2510
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 6
    Ticker: IF2512
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 7
    Ticker: IF2603
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 8
    Ticker: IH2909
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 9
    Ticker: IH2510
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 10
    Ticker: IH2512
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 11
    Ticker: IH2603
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 12
    Ticker: IM2509
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 13
    Ticker: IM2510
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 14
    Ticker: IM2512
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 15
    Ticker: IM2603
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 16
    Ticker: SH000300
    ExchangeID: SH
    PriceTick: 0.01
  -
    TickerIndex: 17
    Ticker: SH000905
    ExchangeID: SH
    PriceTick: 0.01
  -
    TickerIndex: 18
    Ticker: SH000016
    ExchangeID: SH
    PriceTick: 0.01
  -
    TickerIndex: 19
    Ticker: SH000852
    ExchangeID: SH
    PriceTick: 0.01